### PR TITLE
Task-48652:Remove typed letter after selected the user on chat room users suggester

### PR DESCRIPTION
**Pull request by ahmadmido**
**Issue:** The typed letter is still displayed after selecting users from the suggested list.
**Solution**: Add a key to exo-identity-suggester. in fact, the key as participants is the model of the component, each time the list of participants changes when you select a new user, this changes the value of the key, which forces the component to re-render and this will list just the participants and will remove automatically the extra typed text.

### CODE REVIEW

**Comment by ahamdi** [comment]
How does adding a key solve the problem ?

**Comment by ahmadmido** [comment]
> How does adding a key solve the problem ?

yes it resolves the problem

**Comment by ahamdi** [comment]
@ahmadmido Well, when the Key changes, the component is forced to re-render. https://vuejs.org/v2/api/#key
Thus in our case, you put the key as participants which is the model of the component. Each time the list of participants changes when you select a new user, this changes the value of the key, which forces the component to re-render and this will list just the participants and will remove automatically the extra text.

**Comment by ahamdi** [comment]
@ahmadmido This will work-around the current bug. We may need to update the VueJS version if this is already fixed. But you need now to update the description of the PR with excplanation.

**Comment by ahmadmido** [comment]
> @ahmadmido This will work-around the current bug. We may need to update the VueJS version if this is already fixed. But you need now to update the description of the PR with excplanation.

Done the description!

**Review by ahamdi — APPROVED** [review]

**Pull request merged**
