### PR TITLE
Fix for User status Icon not colored on Light Background navbar

### PR DESCRIPTION
**Pull request by teknologist**
Tested on 1.2.0 version of the addon.

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
Hi @teknologist 
Is the issue the same than in https://jira.exoplatform.org/browse/CHAT-357 ?

**Comment by teknologist** [comment]
Yes it seems so. :-)

Weird though because that didn't fix it for me on PLF 4.3 using chat addon 1.2.0 and 1.3.0...

**Comment by thomasdelhomenie** [comment]
I tried with 1.3.0, it works fine on my side.
I also test with 1.2.0 with the fix :

git remote add blessed https://github.com/exoplatform/chat-application.git
git fetch blessed --tags
git checkout 1.3.0
git cherry-pick 63432c94e1121953575590d68de80a1d11142d04

and it works fine also, the icon is colored.

What is you environment ?

**Comment by teknologist** [comment]
Nervermind I might have only tested with add-on 1.2.0.
Sorry...

**Comment by thomasdelhomenie** [comment]
No problem :)
I close the PR.

**Comment by teknologist** [comment]
One thing I am sure though, if you install the latest stable  plf community 4.3.x and do a add-on install chat-community you'll get a faulty version installed, with regards to chat icon color.

**Comment by thomasdelhomenie** [comment]
I checked in the addons catalog. The version 1.2.0 is configured as compatible with PLF 4.3.0 and the version 1.3.0 is configured as compatible with PLF 4.3.1+.
We should probably configure the version 1.3.0 as compatible with PLF 4.3.0+ now I think.
In the meantime, a quick workaround is to install the version 1.3.0 explicitly with : ./addon install exo-chat:1.3.0 --no-compat

What do you mean by "latest stable plf community 4.3.x" ? 4.3.0 ? 4.3.1 ? you built the branch stable/4.3.x by yourself ?

**Pull request closed without merging**
